apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: julh62/exam-kubernetes_fastapi:latest  # Remplacez par le nom de votre image FastAPI
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:password@db:5432/storedb"
