apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin  # Doit correspondre à l'étiquette de votre pod
  ports:
    - protocol: TCP
      port: 80         # Port exposé du service
      targetPort: 8081  # Port du conteneur
  type: NodePort
